[package]
name = "cpi_hyperv"
version = "0.1.1"
edition = "2024"

[lib]
name = "cpi_hyperv"
crate-type = ["cdylib"]

[dependencies]
lib_cpi = { version = "0.1.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"